from environs import Env

env = Env()
env.read_env()

REDIS_HOST = env("QUEUE_REDIS_HOST")
REDIS_PORT = env("QUEUE_REDIS_PORT")

REDIS_URI = f"redis://{REDIS_HOST}:{REDIS_PORT}"


DATABASE_ENGINE = env("DATABASE_ENGINE")
DATABASE_HOST = env("DATABASE_HOST")
DATABASE_PORT = env("DATABASE_PORT")
DATABASE_NAME = env("POSTGRES_DB")
DATABASE_USER = env("POSTGRES_USER")
DATABASE_PASSWORD = env("POSTGRES_PASSWORD")

if DATABASE_ENGINE == 'sqlite':
    DATABASE_URI = f"{DATABASE_ENGINE}://{DATABASE_NAME}"
else:
    if DATABASE_USER:
        DATABASE_URI = f"{DATABASE_ENGINE}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
    else:
        DATABASE_URI = f"{DATABASE_ENGINE}://{DATABASE_HOST}"