version: "3"

services:
  backend:
    build:
      context: ../
    image: paytaca-gifts-backend
    command: [ "supervisord", "-c", "deployment/supervisord_prod.conf", "--nodaemon" ]
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env_prod
    volumes:
      - ../:/app

  postgres:
    image: "postgres:11.1-alpine"
    restart: always
    env_file:
      - .env_prod
    expose:
      - "5432"

  adminer:
    image: adminer
    depends_on: 
      - postgres
    ports:
      - 3000:8080

  redis:
    image: "redis:alpine"
    restart: always

networks:
  default:
    driver: bridge
 